### ISSUE TITLE
Change module name to amphora-authentication or amphora-auth

### ISSUE THREAD

**Issue by james-owen** [clay/amphora-auth#12]
This module originally only handled the integration of Passport.js, but the module will be handling the auth functionality that is being extracted from amphora. Changing the module name will clarify the scope of this module. #11 https://github.com/clay/amphora/pull/635

**Comment by manuelurenah** [comment]
I vote for `amphora-auth` 🙌

**Comment by james-owen** [comment]
Name changed to `amphora-auth`
