### ISSUE TITLE
Disable Local Auth and Login Form

### ISSUE THREAD

**Issue by mrollinsiv** [clay/amphora-auth#33]
Add ability to disable the local auth login form on `/_auth/login`

- Auth form will always show by default
- Login template will check for `CLAY_LOCAL_AUTH === 'false'` and hide the local form

- This fix should be patched backwards to 1.2.x

**Comment by mattoberle** [comment]
Just documenting the release procedure here when this PR is ready (in case I'm out and someone else handles it).

1. (Squash and) merge PR to `master`.
2. `git fetch; git reset --hard origin/master`
3. `npm version patch`
4. `git push origin master`
5. `git push origin tags/v1.3.2`
6. Create GitHub release w/ notes.
7. `npm publish`

For the v1.2.1 release:

1. `git checkout tags/v1.2.0`
2. `git checkout -b v1.2.x`
3. `git cherry-pick <sha1-of-merged-pr>`
4. `npm version patch`
5. `git push origin v1.2.x`
6. `git push origin tags/v1.2.1`
7. Create GitHub release with notes.
8. `npm publish --tag=1.2.x` (to avoid this release being marked as "latest")

**Comment by mattoberle** [comment]
This is all set:

[v1.3.2 (latest)](https://github.com/clay/amphora-auth/releases/tag/v1.3.2)

[v1.2.1 (backport)](https://github.com/clay/amphora-auth/releases/tag/v1.2.1)
